"""empty message

Revision ID: 9c23d34817c0
Revises: ef9eb9d821b0
Create Date: 2024-07-16 20:06:55.427318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c23d34817c0'
down_revision = 'ef9eb9d821b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.drop_table('company_datas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_datas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('image_url', sa.TEXT(), nullable=False),
    sa.Column('catalogue_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['catalogue_id'], ['catalogues.id'], name='fk_company_datas_catalogue_id_catalogues'),
    sa.PrimaryKeyConstraint('id', name='pk_company_datas')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
