"""empty message

Revision ID: edbe889aa480
Revises: 
Create Date: 2024-07-14 18:53:52.474628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edbe889aa480'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('brand', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('price', sa.Text(), nullable=False),
    sa.Column('rating', sa.Text(), nullable=False),
    sa.Column('release_date', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalogues'))
    )
    op.create_table('addcatalogues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('brand', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('price', sa.Text(), nullable=False),
    sa.Column('rating', sa.Text(), nullable=False),
    sa.Column('release_date', sa.Text(), nullable=False),
    sa.Column('catalogue_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['catalogue_id'], ['catalogues.id'], name=op.f('fk_addcatalogues_catalogue_id_catalogues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_addcatalogues'))
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ticket_price', sa.Text(), nullable=False),
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('catalogue_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['catalogue_id'], ['catalogues.id'], name=op.f('fk_news_catalogue_id_catalogues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    op.drop_table('addcatalogues')
    op.drop_table('catalogues')
    # ### end Alembic commands ###
