"""empty message

Revision ID: ef9eb9d821b0
Revises: edbe889aa480
Create Date: 2024-07-15 22:25:03.422787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef9eb9d821b0'
down_revision = 'edbe889aa480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_datas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('catalogue_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['catalogue_id'], ['catalogues.id'], name=op.f('fk_company_datas_catalogue_id_catalogues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_datas'))
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('location')

    op.drop_table('company_datas')
    # ### end Alembic commands ###
